apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: workflow-initiator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow-initiator
  template:
    metadata:
      labels:
        app: workflow-initiator
    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
          name: workflow-initiator
          ports:
            - containerPort: 80
