machines:

  CT-23-KbBBerik123: #1st machine
    tags: #list of tags for 1st machine
      - GRA-TE  -23-0733.PV
      - GRA-TT  -23-0719.PV
      - GRA-YE  -23-0751X.PV
    train_start_date: 2016-01-07T09:11:30+01:00
    train_end_date: 2018-09-15T03:01:00+01:00

  CT-23-KbBBerik1234: #2nd machine
    tags: #list of tags for 2nd machine
      - GRA-TE  -23-0734SEL.PV
      - GRA-YE  -23-0753X.PV
      - GRA-TE  -23-0737B.PV
    train_start_date: 2016-01-20T01:00:04+02:00
    train_end_date: 2018-05-10T15:05:50+02:00

  CT-23-awesomeness: #3rd machine
    tags: #list of tags for 3rd machine
      - GRA-TE  -23-0734SEL.PV
      - GRA-YE  -23-0753X.PV
      - GRA-TE  -23-0737B.PV
    train_start_date: 2016-01-15T13:03:04+02:00
    train_end_date: 2018-03-11T11:05:10+02:00

model:
  sklearn.pipeline.Pipeline:
    steps:
      - sklearn.pipeline.FeatureUnion:
        - sklearn.preprocessing.data.MinMaxScaler
      - gordo_components.model.models.KerasAutoEncoder:
          kind: feedforward_symetric
