machines:
 CT-23-0001:
   tags:
     - GRA-GT  -23-0607.PV
     - GRA-SE -23-0599AX.PV

 Machine-1:
   tags:
     - GRA-GT  -23-0607.PV
     - GRA-TE  -23-0734SEL.PV
     - GRA-YE  -23-0753X.PV
     - GRA-TE  -23-0737B.PV

 Machine-2:
   tags:
     - GRA-GT  -23-0607.PV
     - GRA-TE  -23-0734SEL.PV
     - GRA-YE  -23-0753X.PV
     - GRA-TE  -23-0737C.PV
