machines:
 Machine-1:
   tags:
     - GRA-GT  -23-0607.PV
     - GRA-TE  -23-0734D.PV
     - GRA-TE  -23-0737B.PV
     - GRA-TIT -23-0615.PV

 Machine-2:
   tags:
     - GRA-TE  -23-0737B.PV
     - GRA-TT  -23-0725.PV
     - GRA-TE  -23-0737D.PV

 Machine-3:
   tags:
     - GRA-GT  -23-0607.PV
     - GRA-TE  -23-0734SEL.PV
     - GRA-YE  -23-0753X.PV
     - GRA-TE  -23-0737B.PV
     - GRA-TE  -23-0737C.PV
     - GRA-TE  -23-0737D.PV