machines:
  CT-23-KbBBerik123g: #1st machine
    tags: #list of tags for 1st machine
      - GRA-TE  -23-0733.PV
      - GRA-TT  -23-0719.PV
      - GRA-YE  -23-0751X.PV
    train_start_date: 2016-01-07T09:11:30+01:00
    train_end_date: 2018-09-15T03:01:00+01:00

  CT-23-KbBBerik1234g: #2nd machine
    tags: #list of tags for 2nd machine
      - GRA-TE  -23-0734SEL.PV
      - GRA-YE  -23-0753X.PV
      - GRA-TE  -23-0737B.PV
    train_start_date: 2016-01-20T01:00:04+02:00
    train_end_date: 2018-05-10T15:05:50+02:00

  CT-23-massiveawesomenessMg: #3rd machine
    tags: #list of tags for 3rd machine
      - GRA-TE  -23-0734SEL.PV
      - GRA-YE  -23-0753X.PV
      - GRA-TE  -23-0737B.PV
    train_start_date: 2016-01-15T13:03:04+02:00
    train_end_date: 2018-03-11T11:05:10+02:00
  Auxiliary Systems>Lube Oil System:
    tags:
      - GRA-FT  -23-0111.PV
      - GRA-LT  -23-1001.PV
      - GRA-LT  -23-1105.PV
      - GRA-PDIT-23-1035.PV
      - GRA-PIT -23-1015.PV
      - GRA-PIT -23-1110.PV
      - GRA-TIT -23-1003.PV
      - GRA-TT  -23-1025.PV
    train_end_date: 2017-05-01 00:00:00+00:00
    train_start_date: 2017-03-01 00:00:00+00:00
  Auxiliary Systems>Mineral Lube Oil System:
    tags:
      - GRA-LT  -80-2551.PV
      - GRA-NRA -80-2869.PV
      - GRA-PDIT-80-2577.PV
      - GRA-PT  -80-2581.PV
      - GRA-TT  -80-2552.PV
      - GRA-TT  -80-2580.PV
    train_end_date: 2017-05-01 00:00:00+00:00
    train_start_date: 2017-03-01 00:00:00+00:00
  Auxilliary Systems>Lube Oil System:
    tags:
      - GRA-LT  -23-1205.PV
      - GRA-PIT -23-1210.PV
      - GRA-SE  -23-1290.PV
      - GRA-SE  -23-1291.PV
      - GRA-TIC -23-1025Y.PV
      - GRA-TT  -23-1025.PV
    train_end_date: 2017-05-01 00:00:00+00:00
    train_start_date: 2017-03-01 00:00:00+00:00
  CG-23-0001 - Gearbox>Mechanical:
    tags:
      - GRA-FT  -23-0111.PV
      - GRA-GE  -23-1109A.PV
      - GRA-GE  -23-1109B.PV
      - GRA-GE  -23-1189A.PV
      - GRA-GE  -23-1189B.PV
      - GRA-PIT -23-1015.PV
      - GRA-PT  -23-0111B.PV
      - GRA-TE  -23-1111A.PV
      - GRA-TE  -23-1112A.PV
      - GRA-TE  -23-1113A.PV
      - GRA-TE  -23-1173A.PV
      - GRA-TE  -23-1174A.PV
      - GRA-TE  -23-1175A.PV
      - GRA-TE  -23-1176A.PV
      - GRA-TE  -23-1177A.PV
      - GRA-TE  -23-1178A.PV
      - GRA-TE  -23-1179A.PV
      - GRA-TT  -23-1025.PV
      - GRA-YE  -23-1187X.PV
      - GRA-YE  -23-1187Y.PV
      - GRA-YE  -23-1188X.PV
      - GRA-YE  -23-1188Y.PV
      - GRA-YE  -23-1192.PV
      - GRA-YE  -23-1193X.PV
      - GRA-YE  -23-1193Y.PV
      - GRA-YE  -23-1194X.PV
      - GRA-YE  -23-1194Y.PV
    train_end_date: 2017-05-01 00:00:00+00:00
    train_start_date: 2017-03-01 00:00:00+00:00
  CG-23-0002 - Gearbox>Gearmesh:
    tags:
      - GRA-SE  -23-1291.PV
      - GRA-YE  -23-1292.PV
    train_end_date: 2017-05-01 00:00:00+00:00
    train_start_date: 2017-03-01 00:00:00+00:00
  CG-23-0002 - Gearbox>Mechanical:
    tags:
      - GRA-GE  -23-1209A.PV
      - GRA-GE  -23-1209B.PV
      - GRA-GE  -23-1289A.PV
      - GRA-GE  -23-1289B.PV
      - GRA-SE  -23-1290.PV
      - GRA-SE  -23-1291.PV
      - GRA-TE  -23-1211A.PV
      - GRA-TE  -23-1212A.PV
      - GRA-TE  -23-1213A.PV
      - GRA-TE  -23-1273A.PV
      - GRA-TE  -23-1274A.PV
      - GRA-TE  -23-1275A.PV
      - GRA-TE  -23-1276A.PV
      - GRA-TE  -23-1277A.PV
      - GRA-TE  -23-1278A.PV
      - GRA-TE  -23-1279A.PV
      - GRA-YE  -23-1287X.PV
      - GRA-YE  -23-1287Y.PV
      - GRA-YE  -23-1288X.PV
      - GRA-YE  -23-1288Y.PV
      - GRA-YE  -23-1292.PV
      - GRA-YE  -23-1293X.PV
      - GRA-YE  -23-1293Y.PV
      - GRA-YE  -23-1294X.PV
      - GRA-YE  -23-1294Y.PV
    train_end_date: 2017-05-01 00:00:00+00:00
    train_start_date: 2017-03-01 00:00:00+00:00
  CG-23-0003 - Gearbox>Gearbox Mechanical:
    tags:
      - GRA-GE  -23-1609A
      - GRA-GE  -23-1609B
      - GRA-GE  -23-1689A
      - GRA-GE  -23-1689B
      - GRA-TE  -23-1611A.PV
      - GRA-TE  -23-1612A.PV
      - GRA-TE  -23-1613A.PV
      - GRA-TE  -23-1673A.PV
      - GRA-TE  -23-1674A.PV
      - GRA-TE  -23-1675A.PV
      - GRA-TE  -23-1676A.PV
      - GRA-TE  -23-1677A.PV
      - GRA-TE  -23-1678A.PV
      - GRA-TE  -23-1679A.PV
      - GRA-YE  -23-1687X
      - GRA-YE  -23-1687Y
      - GRA-YE  -23-1688X
      - GRA-YE  -23-1688Y
      - GRA-YE  -23-1692
      - GRA-YE  -23-1693X
      - GRA-YE  -23-1693Y
      - GRA-YE  -23-1694X
      - GRA-YE  -23-1694Y
    train_end_date: 2017-05-01 00:00:00+00:00
    train_start_date: 2017-03-01 00:00:00+00:00
  
model:
  sklearn.pipeline.Pipeline:
    steps:
      - sklearn.pipeline.FeatureUnion:
        - sklearn.preprocessing.data.MinMaxScaler
      - sklearn.preprocessing._function_transformer.FunctionTransformer:
          func: gordo_components.model.transformer_funcs.general.multiply_by
          kw_args:
            factor: 1
      - gordo_components.model.models.KerasAutoEncoder:
          kind: feedforward_symetric
