machines:
  - name: test-asgard
    dataset:
      type: TimeSeriesDataset
      tags: #list of tags
      - asgb.19ZT3950%2FY%2FPRIM
      - asgb.19PST3925%2FDispMeasOut%2FPRIM
      - asgb.19PT3905%2FY%2F5mMID
      train_start_date: 2014-07-01T00:10:00+00:00
      train_end_date: 2018-01-01T00:00:00+00:00

model:
  sklearn.pipeline.Pipeline:
    steps:
      - sklearn.preprocessing.data.MinMaxScaler
      - gordo_components.model.models.KerasAutoEncoder:
          kind: feedforward_symetric
