machines:
  - name: powerslester
    dataset:
      type: TimeSeriesDataset
      tags: 
      - NINENINE.UISFLD::NNWAERYDR02.WHCSGPRS
      - NINENINE.UISFLD::NNWAERYDR02.WHTBGPRS
      - NINENINE.UISFLD::NNWAERYDR02.GASFLW  
      train_start_date: 2018-06-10T00:00:00+01:00
      train_end_date: 2018-06-11T00:00:00+01:00
    model:
      sklearn.pipeline.Pipeline:
        steps:
        - sklearn.pipeline.FeatureUnion:
          - sklearn.preprocessing.data.StandardScaler
        - gordo_components.model.models.KerasAutoEncoder:
            kind: feedforward_model
            enc_dim: [4,2]
            dec_dim: [4]
            enc_func: [tanh,tanh]
            dec_func: [tanh]
